# Generated by Django 6.0.1 on 2026-03-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_label_options_remove_task_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='имя'),
        ),
    ]
